### PR TITLE
#20 - Integrate auto linting during Travis Build

### PR DESCRIPTION
**Pull request by StegSchreck**

### CODE REVIEW

**Comment by StegSchreck** [comment]
Travis is now red for this PR because of findings during linting. The scope for the linting can be adjusted using a `.pylintrc` file in repo next to the `.travis.yml`.

**Comment by StegSchreck** [comment]
I fixed the easy ones. There are some findings, especially about `get_details` method, which I will leave for you, as this might need some more refactoring and I do not consider that part of this ticket.

**Comment by aashutoshrathi** [comment]
@StegSchreck I agree, just fix those, which you feel can be done easily and leave rest to me.

**Comment by aashutoshrathi** [comment]
Also fix the conflicts 😅

**Comment by StegSchreck** [comment]
> More conflicts @StegSchreck
> I'll merge as soon as you resolve them
> And then build can be handled in a separate PR

done.

**Pull request merged**
