### PR TITLE
docopt cli and lint cleanup

### PR DESCRIPTION
**Pull request by Grokzen**
I reworked the cli handling code to use docopt instead of argparse. Looks much cleaner now. I also threw in some general lint cleanup of the imports and of the code in general. Anything you do not like, just mark it and i revert it back.

### CODE REVIEW

**Comment by Grokzen** [comment]
I could not verify all code paths manually as some of them had KeyErrors in them. Overall it looks to work as expected.

**Comment by aashutoshrathi** [comment]
Can you fix travis?

**Comment by aashutoshrathi** [comment]
@Grokzen Please add your contribution to changelog as of next version, so that I'll merge and bump the version.
Thanks

**Comment by aashutoshrathi** [comment]
And please resolve conflicts

**Comment by Grokzen** [comment]
That should do it i think

**Comment by aashutoshrathi** [comment]
Just add yourself to CHANGELOG.md and we are good to go

**Comment by aashutoshrathi** [comment]
Make it 1.4.1 and also please change last to version that file to 1.3.0 and 1.4.0

**Comment by Grokzen** [comment]
@aashutoshrathi döne

**Pull request merged**
