### PR TITLE
added optional dictionary returns to get_* functions

### PR DESCRIPTION
**Pull request by athulpn**

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
It should not be printed, if we just want it in form of a dictionary.

**Comment by athulpn** [comment]
changed it

**Comment by aashutoshrathi** [comment]
resolve conflicts

**Comment by athulpn** [comment]
New to git😁, can you help me out to resolve merge conflicts.

**Comment by athulpn** [comment]
@aashutoshrathi resolved conflicts

**Pull request closed without merging**
