### PR TITLE
Issue#53

### PR DESCRIPTION
**Pull request by gpetrousov**
Please review this PR for #52 

- added bumpversion config file
- updated requirements with bumpversion package

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
Can you also update README for how to use bump version for devs?

**Comment by gpetrousov** [comment]
@aashutoshrathi - Please review the updated PR.

I updated bumpversion based on how you did releases in past commits.
I'm not exactly an expert on this so let me know if it needs more fixes.

**Comment by gpetrousov** [comment]
@aashutoshrathi - Please review the updated PR.

I updated bumpversion based on how you did releases in past commits.
I'm not exactly an expert on this so let me know if it needs more fixes.

**Comment by gpetrousov** [comment]
@aashutoshrathi - Please review the updated PR.

I updated bumpversion based on how you did releases in past commits.
I'm not exactly an expert on this so let me know if it needs more fixes.

**Pull request merged**
