### PR TITLE
Issue#7

### PR DESCRIPTION
**Pull request by gpetrousov**
The fill_data() function still needs to be modified so it no longer retains today's events, but instead spans across the dates flags.

### CODE REVIEW

**Comment by gpetrousov** [comment]
@aashutoshrathi - Please review this PR.
I tried to DRY, however, there are changes needed to be made to the flow and not sure how you want to make this work.

Summary:
 - now you can use --since and --until flags
 - events are filtered based on the flags above
 - fill_data is populated based on the flags above
 - original functionality maintained

**Comment by aashutoshrathi** [comment]
Looks good to me, can you please post a GIF as demo. 😅

**Comment by gpetrousov** [comment]
demo

**Comment by aashutoshrathi** [comment]
Please resolve conflicts.

**Comment by gpetrousov** [comment]
Resolved! :)

**Pull request merged**
